# Generated by Django 2.0.3 on 2018-03-10 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0009_auto_20180310_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProgrammerProfile.Person'),
        ),
    ]
