# Generated by Django 2.0.3 on 2018-03-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0025_auto_20180311_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
