# Generated by Django 2.0.3 on 2018-03-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammerProfile', '0029_auto_20180311_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('CountryOfOrigin', models.CharField(max_length=255)),
                ('ProfilePic', models.FileField(upload_to='')),
            ],
        ),
    ]
